# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoDataDialog
                                 A QGIS plugin
 This plugin gathers cz/sk data sources.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-04
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Test
        email                : test
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import configparser
import sys
import webbrowser

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt import QtGui
from qgis.utils import iface
from qgis.core import *
from qgis.PyQt.QtGui import *
from qgis.PyQt.QtCore import *
from qgis.PyQt.QtWidgets import *
from qgis.gui import *

owslib_exists = True
try:
    from owslib.wps import WebProcessingService
    from owslib.util import getTypedValue
except:
    owslib_exists = False

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'wps_dialog_base.ui'))


class WpsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, iface, parent=None):
        """Constructor."""
        super(WpsDialog, self).__init__(parent)
        self.iface = iface
        self.setupUi(self)
        self.pushButtonAbout.setIcon(QIcon(os.path.join(os.path.dirname(__file__), "icons/cropped-opengeolabs-logo-small.png")))
        self.pushButtonAbout.clicked.connect(self.showAbout)
        if owslib_exists and self.check_owslib_fix():
            self.pushButtonLoadProcesses.clicked.connect(self.load_processes)
            self.pushButtonLoadProcess.clicked.connect(self.load_process)
            self.verticalLayoutInputs = QVBoxLayout(self.tabInputs)
        else:
            QMessageBox.information(None, QApplication.translate("WPS", "ERROR:", None), QApplication.translate("WPS", "You have to install OWSlib with fix.", None))

    def check_owslib_fix(self):
        try:
            val = getTypedValue('integer', None)
            return True
        except:
            return False

    def load_processes(self):
        try:
            self.wps = WebProcessingService(self.lineEditWpsUrl.text())
            self.wps.getcapabilities()
            processes = [x.identifier for x in self.wps.processes]
            self.comboBoxProcesses.clear()
            for proc in processes:
                self.comboBoxProcesses.addItem(proc)
        except:
            QMessageBox.information(None, QApplication.translate("WPS", "ERROR:", None), QApplication.translate("WPS", "Error reading processes", None))

    def get_all_layers_input(self):
        return QgsMapLayerComboBox()

    def get_input(self, type, default_value):
        # TODO check types
        if type == 'ComplexData':
            return self.get_all_layers_input()
        else:
            le = QLineEdit()
            le.setText(str(default_value))
            return le

    def load_process(self):
        processid = self.comboBoxProcesses.currentText()
        if processid != "":
            process = self.wps.describeprocess(processid)
            if process.abstract is not None:
                for i in reversed(range(self.verticalLayoutInputs.count())):
                    self.verticalLayoutInputs.itemAt(i).widget().setParent(None)
                self.labelProcessDescription.setText(process.abstract)
                for x in process.dataInputs:
                    # TODO put into some list with identifiers
                    # x.identifier
                    le = self.get_input(x.dataType, x.defaultValue)
                    self.verticalLayoutInputs.addWidget(le)
                self.tabInputs.setLayout(self.verticalLayoutInputs)


    def showAbout(self):
        try:
            webbrowser.get().open("http://opengeolabs.cz")
        except (webbrowser.Error):
            self.iface.messageBar().pushMessage(QApplication.translate("GeoData", "Error", None), QApplication.translate("GeoData", "Can not find web browser to open page about", None), level=Qgis.Critical)
